# azure-pipelines.yml
# Builds and deploys to Azure Container Apps, using secrets that are manually
# managed in the Azure Portal's "Secrets" section.

trigger:
- main

variables:
  # --- General Settings - UPDATE THESE ---
  azureSubscription: 'Microsoft Azure Sponsorship(0e00a747-e3da-4a5f-b795-6f0237cd94f6)'
  resourceGroup: 'keycloak'
  
  # --- Container Registry & App Settings - UPDATE THESE ---
  containerRegistry: 'devopstest1'
  containerAppName: 'keycloak-container' # IMPORTANT: This must match the name of your app in Azure
  imageRepository: 'keycloak-azure'
  dockerfilePath: 'keycloak-26.3.1/Dockerfile'

  # The hostname of your container app.
  KC_HOSTNAME: 'keycloak-container.jollyhill-e899b4ae.centralindia.azurecontainerapps.io'

  # --- Pipeline Variables ---
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: Build
    displayName: 'Build and Push'
    steps:
    - task: Docker@2
      displayName: 'Build and push image to ACR'
      inputs:
        command: buildAndPush
        containerRegistry: $(containerRegistry)
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        tags: |
          $(tag)
          latest

- stage: Deploy
  displayName: 'Deploy to Azure Container Apps'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: 'Deploy Container Image'
    steps:
    # NOTE: The step for setting secrets with Azure CLI has been removed.
    # This pipeline now assumes secrets already exist in the Container App.
    
    # CORRECTED YAML - PLEASE USE THIS EXACT BLOCK

- task: AzureContainerApps@1
  displayName: 'Deploy to Container App'
  inputs:
    azureSubscription: $(azureSubscription)
    containerAppName: $(containerAppName)
    resourceGroup: $(resourceGroup)
    imageToDeploy: '$(containerRegistry)/$(imageRepository):$(tag)'
    
  # 'registries' is NOT under 'inputs'. It is at the same level.
  registries:
    # The '-' starts a list item.
    # 'server' and 'identity' are properties of this same list item.
    - server: $(containerRegistry)
      identity: 'system' 

  # The environmentVariables block also lines up with 'inputs' and 'registries'.
  environmentVariables: |
    KC_BOOTSTRAP_ADMIN_USERNAME=admin
    KC_BOOTSTRAP_ADMIN_PASSWORD=secretref:keycloak-admin-password
    KC_DB_URL=secretref:db-url
    KC_DB_USERNAME=secretref:dbuser
    KC_DB_PASSWORD=secretref:dbpass
    KC_HTTP_ENABLED=true
    KC_PROXY_HEADERS=xforwarded
    KC_HOSTNAME=$(KC_HOSTNAME)