version: '3.8'

services:
  keycloak:
    build:
      context: ./keycloak-26.3.1
      dockerfile: Dockerfile
      args:
        DBNAME: ${DBNAME}
        DBUSER: ${DBUSER}
        DBPASS: ${DBPASS}
        
    container_name: custom-keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      DBNAME: ${DBNAME}
      DBUSER: ${DBUSER}
      DBPASS: ${DBPASS}
    depends_on:
      - postgres
    volumes:
      - keycloak_data:/opt/keycloak/data

  postgres:
    image: postgres:15
    container_name: keycloak-db
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}
    ports:
      - "${DBPORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  keycloak_data:
  postgres_data:
